resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'
this_is_a_map 'yes'
data_file 'GTXD_PARENTING_DATA' 'texas.meta'

data_file 'DLC_ITYP_REQUEST' 'stream/texas_props.ityp'
file 'stream/texas_1.ydr'
file 'stream/texas_2.ydr'
file 'stream/texas_3.ydr'
file 'stream/texas_4.ydr'
file 'stream/texas_5.ydr'
file 'stream/texas_6.ydr'
file 'stream/texas_7.ydr'
file 'stream/texas_8.ydr'
file 'stream/texas_9.ydr'
file 'stream/texas_10.ydr'
file 'stream/texas_11.ydr'
file 'stream/texas_12.ydr'
file 'stream/texas_13.ydr'
file 'stream/texas_full.ytd'
file 'texas.meta'